# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress Training

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v4
    - name: Use Node.js 16.13.2 to run Cypress Test Automation
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.2
    - name: Cypress Run
      working-directory: ./
      run: |
        npm install
        npm run cy:run
      continue-on-error: true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Gea Test Automation Artifact at ${{ steps.date.outputs.date }} 
        path: "./cypress/results"
    
